[2021-11-21 15:56:45,349: INFO: 02_transfer_learning_even_odd]: 
********************
[2021-11-21 15:56:45,349: INFO: 02_transfer_learning_even_odd]: >>>>> stage transfer learning started <<<<<
[2021-11-21 15:56:45,351: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-21 15:56:46,608: ERROR: 02_transfer_learning_even_odd]: No file or directory found at artifacts\models\base_model.h5
Traceback (most recent call last):
  File "src/02_transfer_learning_even_odd.py", line 104, in <module>
    main(config_path=parsed_args.config)
  File "src/02_transfer_learning_even_odd.py", line 55, in main
    base_model = tf.keras.models.load_model(base_model_path)
  File "C:\Users\Sasmitabhoi\anaconda3\envs\Transfer-Learning\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Sasmitabhoi\anaconda3\envs\Transfer-Learning\lib\site-packages\keras\saving\save.py", line 209, in load_model
    raise IOError(f'No file or directory found at {filepath}')
OSError: No file or directory found at artifacts\models\base_model.h5
